[package]
name = "tudelft-nes-test"
version = "2.1.0"
edition = "2021"
authors = [
    "Victor Roest <victor@xirion.net>",
    "Jonathan Dönszelmann <jonabent@gmail.com>",
]
description = "support library for the 'software fundamentals' project for the TU Delft"
repository = "https://gitlab.ewi.tudelft.nl/software-fundamentals/nes-emulator-testing"
keywords = ["NES", "tudelft"]
categories = ["emulators", "development-tools::testing"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tudelft-nes-ppu = { version = "2.1.0", path = "../tudelft-nes-ppu" }
thiserror = "1"
bitflags = "2.4"
log = "0.4"
